import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/Layout";
import profilePic from "../../public/images/profile/profile-pic.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import About from "./About";
import Skills from "@/components/Skills";
import Experience from "@/components/Experience";
import Projects from "./projects";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full ">
            <div className="w-[40%]">
              <Image
                src={profilePic}
                alt="YesidTorres"
                className="w-full h-auto"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <p className="!text-left my-4 text-base font-medium mr-auto">
                Hi,👋 My name is Yesid and I am a
              </p>
              <AnimatedText
                text="Frontend Web Developer."
                className="!text-6xl !text-left"
              />
              <p className="my-4 text-base font-medium">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/dummy.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light border-2 border-solid border-transparent hover:text-dark hover:border-dark dark:bg-light dark:text-black hover:dark:bg-dark hover:dark:text-light hover:dark:border-light"
                  download={true}
                >
                  Resume
                  <LinkArrow className="w-6 ml-1" />
                </Link>
                <Link
                  href="mailto:mautorres15@hotmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark p-2.5 rounded-lg border-2 border-solid border-dark dark:text-light dark:border-light"
                >
                  Contact me
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />
      </main>
      <div className="pt-2">
        <About />
        <Skills />
        <Experience />
        <Projects />
      </div>
    </>
  );
}
