import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/Layout";
import profilePic from "../../public/images/profile/profile-pic.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import About from "./About";
import Skills from "@/components/Skills";
import Experience from "@/components/Experience";
import Projects from "./projects";
import ContactForm from "./Contact";
import GoUpButton from "@/components/GoUpButton";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Mauricio Suescun Portfolio</title>
        <meta
          name="Mauricio Suescun's Portfolio "
          content="Generated by create next app"
        />
      </Head>
      <main
        id="home"
        className="flex items-center text-dark w-full min-h-screen dark:text-light"
      >
        <Layout className="pt-2 md:pt-4 sm:pt-4">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-[40%] md:w-full">
              <Image
                src={profilePic}
                alt="YesidTorres"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <p className="!text-left my-4 text-base font-medium mr-auto">
                Hi there!👋, My name is Mauricio and I am a
              </p>
              <AnimatedText
                text="Frontend Developer."
                className=" !text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="mt-4 text-base font-medium">
                As a skilled frontend developer, I am dedicated to turning ideas
                into innovative web applications. Feel free to explore my
                featured projects and my experience working with cutting-edge
                technologies—all of this is in service of your next project.
              </p>

              <div className="flex items-center self-start mt-4 lg:self-center">
                <Link
                  href="/CV Yesid Mauricio Torres Suescun (en).pdf"
                  target={"_blank"}
                  className="flex items-center bg-primary border-dark text-dark p-2.5 xs:w-32 sm:w-32 px-6 rounded-lg text-lg font-semibold hover:bg-light border-2 border-solid hover:text-dark hover:border-dark dark:bg-primary dark:text-black hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  Resume
                  <LinkArrow className="w-6 ml-1" />
                </Link>
                <Link
                  href="mailto:mautorres15@hotmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-semibold capitalize text-dark p-2.5 rounded-lg border-2 border-solid border-dark dark:text-light dark:border-light hover:bg-primary  hover:dark:text-dark hover:dark:border-primary md:text-base"
                >
                  Contact me
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <div className="z-50">
          <HireMe />
        </div>
      </main>
      <div className="pt-2">
        <div id="about">
          <About />
        </div>
        <div id="skills">
          <Skills />
        </div>
        <div id="experience">
          <Experience />
        </div>
        <div id="projects">
          <Projects />
        </div>
        <div id="contact" className="px-16 md:px-0 sm:px-0">
          <ContactForm />
        </div>
      </div>
      <GoUpButton />
    </>
  );
}
